name = "fullstack-astro-cloudflare"
compatibility_flags = ["nodejs_als"]
compatibility_date = "2024-05-12"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "APP_DB"                                   # i.e. available in your Worker on env.APP_DB
database_name = "fullstack-astro-cloudflare-db"
database_id = "40db7fa1-c958-415c-8d63-8d4966211374"
migrations_dir = "./drizzle"

[[r2_buckets]]
binding = 'APP_BUCKET'
bucket_name = 'astro'
